const BACKEND_URL = process.env.BACKEND_URL || "http://localhost:4000";
module.exports = [
  // WIRES

  {
    name: "Copper House Wire",
    category: "wire",
    image: `${BACKEND_URL}/images/wire_1.png`,
    new_price: 450,
    old_price: 550,
  },
  {
    name: "Flexible Cable",
    category: "wire",
    image: `${BACKEND_URL}/images/wire_2.png`,
    new_price: 520,
    old_price: 620,
  },
  {
    name: "Armoured Cable",
    category: "wire",
    image: `${BACKEND_URL}/images/wire_3.png`,
    new_price: 1200,
    old_price: 1400,
  },
  {
    name: "Solar Cable",
    category: "wire",
    image: `${BACKEND_URL}/images/wire_4.png`,
    new_price: 700,
    old_price: 850,
  },
  {
    name: "Multi Core Cable",
    category: "wire",
    image: `${BACKEND_URL}/images/wire_5.png`,
    new_price: 950,
    old_price: 1100,
  },
  {
    name: "Aluminium Cable",
    category: "wire",
    image: `${BACKEND_URL}/images/wire_6.png`,
    new_price: 800,
    old_price: 950,
  },
  {
    name: "PVC Cable",
    category: "wire",
    image: `${BACKEND_URL}/images/wire_7.png`,
    new_price: 400,
    old_price: 500,
  },
  {
    name: "Industrial Cable",
    category: "wire",
    image: `${BACKEND_URL}/images/wire_8.png`,
    new_price: 1500,
    old_price: 1800,
  },
  {
    name: "Fire Resistant Cable",
    category: "wire",
    image: `${BACKEND_URL}/images/wire_9.png`,
    new_price: 900,
    old_price: 1050,
  },
  {
    name: "Coaxial Cable",
    category: "wire",
    image: `${BACKEND_URL}/images/wire_10.png`,
    new_price: 350,
    old_price: 450,
  },
  {
    name: "Earthing Wire",
    category: "wire",
    image: `${BACKEND_URL}/images/wire_11.png`,
    new_price: 600,
    old_price: 720,
  },
  {
    name: "Control Cable",
    category: "wire",
    image: `${BACKEND_URL}/images/wire_12.png`,
    new_price: 1100,
    old_price: 1350,
  },

  // SWITCHES

  {
    name: "Modular Switch",
    category: "switches",
    image: `${BACKEND_URL}/images/switch_1.png`,
    new_price: 120,
    old_price: 150,
  },
  {
    name: "Smart Switch",
    category: "switches",
    image: `${BACKEND_URL}/images/switch_2.png`,
    new_price: 650,
    old_price: 800,
  },
  {
    name: "Fan Regulator",
    category: "switches",
    image: `${BACKEND_URL}/images/switch_3.png`,
    new_price: 350,
    old_price: 450,
  },
  {
    name: "Dimmer Switch",
    category: "switches",
    image: `${BACKEND_URL}/images/switch_4.png`,
    new_price: 420,
    old_price: 500,
  },
  {
    name: "Socket",
    category: "switches",
    image: `${BACKEND_URL}/images/switch_5.png`,
    new_price: 180,
    old_price: 220,
  },
  {
    name: "USB Socket",
    category: "switches",
    image: `${BACKEND_URL}/images/switch_6.png`,
    new_price: 480,
    old_price: 550,
  },
  {
    name: "Touch Switch",
    category: "switches",
    image: `${BACKEND_URL}/images/switch_7.png`,
    new_price: 950,
    old_price: 1150,
  },
  {
    name: "Waterproof Switch",
    category: "switches",
    image: `${BACKEND_URL}/images/switch_8.png`,
    new_price: 550,
    old_price: 650,
  },
  {
    name: "DP Switch",
    category: "switches",
    image: `${BACKEND_URL}/images/switch_9.png`,
    new_price: 250,
    old_price: 320,
  },
  {
    name: "Bell Switch",
    category: "switches",
    image: `${BACKEND_URL}/images/switch_10.png`,
    new_price: 140,
    old_price: 180,
  },
  {
    name: "Extension Board",
    category: "switches",
    image: `${BACKEND_URL}/images/switch_11.png`,
    new_price: 650,
    old_price: 780,
  },
  {
    name: "Industrial Switch",
    category: "switches",
    image: `${BACKEND_URL}/images/switch_12.png`,
    new_price: 980,
    old_price: 1200,
  },

  // CIRCUIT BREAKERS

  {
    name: "MCB",
    category: "circuitbreaker",
    image: `${BACKEND_URL}/images/cb_1.png`,
    new_price: 350,
    old_price: 420,
  },
  {
    name: "MCCB",
    category: "circuitbreaker",
    image: `${BACKEND_URL}/images/cb_2.png`,
    new_price: 2500,
    old_price: 2900,
  },
  {
    name: "RCCB",
    category: "circuitbreaker",
    image: `${BACKEND_URL}/images/cb_3.png`,
    new_price: 1450,
    old_price: 1650,
  },
  {
    name: "ELCB",
    category: "circuitbreaker",
    image: `${BACKEND_URL}/images/cb_4.png`,
    new_price: 1200,
    old_price: 1450,
  },
  {
    name: "Isolator",
    category: "circuitbreaker",
    image: `${BACKEND_URL}/images/cb_5.png`,
    new_price: 800,
    old_price: 950,
  },
  {
    name: "Fuse Unit",
    category: "circuitbreaker",
    image: `${BACKEND_URL}/images/cb_6.png`,
    new_price: 650,
    old_price: 780,
  },
  {
    name: "Distribution Box",
    category: "circuitbreaker",
    image: `${BACKEND_URL}/images/cb_7.png`,
    new_price: 1800,
    old_price: 2200,
  },
  {
    name: "Contactor",
    category: "circuitbreaker",
    image: `${BACKEND_URL}/images/cb_8.png`,
    new_price: 2100,
    old_price: 2500,
  },
  {
    name: "Relay",
    category: "circuitbreaker",
    image: `${BACKEND_URL}/images/cb_9.png`,
    new_price: 450,
    old_price: 550,
  },
  {
    name: "Motor Starter",
    category: "circuitbreaker",
    image: `${BACKEND_URL}/images/cb_10.png`,
    new_price: 2900,
    old_price: 3400,
  },
  {
    name: "Changeover Switch",
    category: "circuitbreaker",
    image: `${BACKEND_URL}/images/cb_11.png`,
    new_price: 1350,
    old_price: 1600,
  },
  {
    name: "Surge Protector",
    category: "circuitbreaker",
    image: `${BACKEND_URL}/images/cb_12.png`,
    new_price: 950,
    old_price: 1150,
  },
];
